### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by y2k4life** [erikdietrich/ChessTDD#1]
I cloned the project. I'm getting a missing files notification and compile errors. The are the PawnMoves.feature, PawnMoves.feature.cs, QueenMoves.feature, QueenMoves.feature.cs files. I see the QueenMoves.feature.cs file in the repository, more than likely I get a file not found due to the associated .features file. -Guy

**Comment by erikdietrich** [comment]
Sorry 'bout that, and thanks for the heads up.  I'm on the road right now (without access to my development environment), but when I get home on Friday, I'll get the missing files up and make sure that it compiles.  When I first started this project, I used to have 2 different dev machines that I worked on, which was a nice check and balance.  Now that I don't any longer, it looks like things are slipping through the cracks :(

**Comment by y2k4life** [comment]
If my work is not too busy I will be a means of checking. On a side note this is a great series. Once and if this is ever done you might want to package it up as a complete coarse. You can also target different markets besides TDD. There is ATDD, NCrunch, SpecFlow, inside-outside, outside-inside, etc... I know much about TDD, but learning SpecFlow, and NCrunch, is great. Although I don't have NCrunch I'm still able to fallow along, just a bit more challenging. I think I know what I want for my birthday. I do see you use CodeRush, but for the most part I can do refactoring without it, but NCrunch is nice. I have used CodeRush and ReSharper in the past. But one thing I try to do, is be a coder on a budget. It is part of my philosophy that anyone can code. Making it affordable attracts a wider audience of potential programmers. Adding extra stuff at a price mitigates that philosophy.

**Comment by erikdietrich** [comment]
Thanks for the feedback and encouragement!  And, if you're willing, I definitely appreciate the help in checking for validity.

It sounds like you have some good thoughts on the subject of marketing.  Is this something you're experienced with?  (I'm very much not, and just kind of stumbling my way through, trying to figure it out).

**Comment by y2k4life** [comment]
Your welcome, no marketing skills here. I have worked in that domain building websites. I also have some knowledge from the past working with someone who marketed software I created. although that project went no where I did learn.

**Comment by erikdietrich** [comment]
Sorry for the delay, but I added the three missing files.  Hopefully it should compile and work properly now.  I'll hold off closing the issue until I get confirmation (either from you or if I get a chance to pull it down elsewhere and build it)

**Comment by y2k4life** [comment]
I did a pull, the project was updated and compiled without error. I ran the tests with a result of 123 passed.

**Comment by erikdietrich** [comment]
Glad to hear it!
